# Site settings
title: Sujan's Blog
description: My blog about coding
keywords: Modern, Blogging, Fun
author: Sujan
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
